- title: Web Development
  icon: code
  text: >
    Web development is based on <b>Ruby on Rails</b> technology.  Having a lot of experience and broad
    knowledge we deliver software so that you have it on time and that it fits best to project's requirements

- title: Free Code Audit
  icon: chart-bar
  text: >
    We implement this engineering practice in terms of <b>agile development methodology</b>.
    Main goal code review is to identify differences in code writing style according to <b>Ruby style guide</b>.
    To provide this convention we use rubocob gem and make the description of problem-solving in a short time.
- title: Maintenance & Support
  icon: gauge
  class: omega
  text: >
    We offer web development project management, maintenance, and support services to achieve your
    business needs.Our team keeps this process strong with <b>regular checkups</b> and <b>web analytic tools</b>.
